
spring:
  application:
    name: mist-play
  datasource:
    url: jdbc:mysql://192.168.100.200:3306/mist?serverTimezone=Asia/Shanghai
    username: root
    password: root
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
server:
  port: 8082
