server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.100.200:3306/mist?serverTimezone=GMT%2b8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: false
    suffix: .html
    request-context-attribute: request
  redis:
    host: 192.168.100.200
  security:
    user:
      password: password
