spring:
  datasource:
    url: jdbc:mysql://localhost/mist
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: false
    suffix: .html
    request-context-attribute: request
server:
  port: 8081