server:
  port: 8080

spring:
  application:
    name: mist-admin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.100.200/mist
    username: root
    password: root
    druid:
      #      filters: stat, wall, log4j, config
      initial-size: 1
      min-idle: 1
      max-active: 100
      max-wait: 60000
      test-while-idle: true
      validation-query: select 'x'
  cloud:
    consul:
      host: localhost
      port: 8500

    #    name: ${
#    name: @project.name@
