server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    url: jdbc:mysql://localhost
    username: root
    password: root
    druid:
      filters: stat,wall,log4j,config
      initial-size: 1
      min-idle: 1
      max-active: 100
      max-wait: 60000
      test-while-idle: true
      validation-query: select 'x'
