spring:
  application:
    name: mist-gateway
  cloud:
    consul:
      host: vm
      port: 8500
    gateway:
      routes:
        - id: mist-payment
          url: mist-payment

server:
  port: 3344