server:
  port: 8001
spring:
  application:
    name: mist-payment
  cloud:
    consul:
      host: vm
      port: 8500
      discovery:
        health-check-critical-timeout: 10s
logging:
  pattern:
    console: "%date %clr(%5level) - %m%n"