server:
  port: 8001
spring:
  application:
    name: mist-payment
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
  instance:
    prefer-ip-address: true
