server:
  port: 8100
spring:
  application:
    name: mist-consumer
  cloud:
    nacos:
      discovery:
        server-addr: vm:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'